#!/usr/bin/dash

out_exe="$1"

run_cmd_in_subdir() {
    local cmd="$1"
    local subdir="$2"

    for fi in $(ls -t -r "$subdir"); do
        fullname="$subdir/$fi"
        echo -n "testing $cmd on ${subdir}/${fi}... "

        input=$(head -n 1 "$fullname")
        result=$("$cmd" "$input")
        correct_result=$(tail -n 1 "$fullname")

        if [ "$result" = "$correct_result" ]; then
            echo "OK."
            continue
        else
            echo "FAILED TEST:"
            echo "\tinput: $input"
            echo "\tresult: \t$result"
            echo "\tcorrect result: $correct_result"
            exit 1
        fi
    done
}

run_failing_cmd_in_subdir() {
    local cmd="$1"
    local subdir="$2"

    for fi in $(ls -t -r "$subdir"); do
        fullname="$subdir/$fi"
        echo -n "testing $cmd - < $fullname ..."
        "$cmd" '-' < "$fullname" > /dev/null && exit 1
        echo " OK."
    done

}

main() {
    echo "=== testing expression parser... "

    run_cmd_in_subdir "$out_exe" "test/tests"
    run_cmd_in_subdir "$out_exe" "test/new_tests"
    run_cmd_in_subdir "$out_exe" "test/whitespace_tests/"
    run_cmd_in_subdir "$out_exe" "test/whitespace_free_tests/"
    run_cmd_in_subdir "$out_exe" "test/new_whitespace_tests"
    run_cmd_in_subdir "$out_exe" "test/prefix_ops"
    run_cmd_in_subdir "$out_exe" "test/rational"
    run_cmd_in_subdir "$out_exe" "test/exponents"
    echo "=== all expression parser tests passed :^)"

    echo "=== now checking invalid inputs..."
    run_failing_cmd_in_subdir "$out_exe" "test/new_failing_tests"
    echo "=== all bad tests failed :^)"
}

main
